### ISSUE TITLE
Documentation/Help with running localtunnel.server

### ISSUE THREAD

**Issue by sundayScoop** [angelobreuer/localtunnel.net#22]
I'm attempting to run a localtunnel server locally in a similar way a-stankevich did in issue #16 although I'm getting a strange error. 

My setup is on Windows 11, where I got a simple python http server running on port 8000. This is what I want to tunnel.
``` python -m http.server 8000 ```

The client is the localtunnel client provided by @angelobreuer.
```localtunnel -s http://localhost --port 8000 --no-dashboard -v http```

The localtunnel server is the latest docker image.
```docker run --rm -it --env Dns__Zone=localhost -p 80:80 angelobreuer/localtunnel-server```

### **The error I'm getting is this in the localtunnel client:** 
![image](https://user-images.githubusercontent.com/87186823/210937332-e4f8bb76-205c-41b3-b117-f60aecdaae37.png)

### **This is the log from the localtunnel server:**
![image](https://user-images.githubusercontent.com/87186823/210937429-4bb7a124-123a-4bed-ae78-0cc8a3aeaaa8.png)

A question I had is - Do I need an nginx server to handle the http(s) requests like the original? I didn't see any mention of this in the issues.

I tried searching for documentation on running the .net localtunnel server (as it's so much more up to date than the JS one) but all I could find where commands in issues. If there's any documentation available I'd love to have a read. 

Thanks!

**### UPDATE**

The error from before was my machine's failure in resolving any wildcard localhost domain. I added this line in c:\windows\system32\drivers\etc\hosts 
```127.0.0.1 surf.localhost``` 

And now the client repeatedly displays these messages:
![image](https://user-images.githubusercontent.com/87186823/210940371-469c21e5-3da4-4b16-b158-2fff9492b39a.png)

Server logs:
![image](https://user-images.githubusercontent.com/87186823/210940445-33f8a48c-1db0-41dd-892f-c6c1682197e6.png)

I can see the logs show https://surf.localhost (HTTPS!). Does this mean I need an nginx?

**Comment by angelobreuer** [comment]
The "connection refused" error comes from the localtunnel client as it fails to connect to the port returned by the localtunnel server API. It works in that way, that the client contacts the API server and asks for a port to be open to transfer data from and to the tunnel. The port is opened by allocating a random port from the operating system. This is some kind of flaw of the original localtunnel server idea. You need to open all TCP ports which could be allocated on the machine.

My comment in the issue about the localtunnel server (#12) is incorrect, as it only opens the port 80. You need to either open all ports, or use the host network. Use the command from the main issue comment: `docker run -it --env Dns__Zone=localtunnel.net --network host angelobreuer/localtunnel-server`. 

The API also returns an externally accessible address (at least what it thinks to be externally accessible) allocated from the DNS zone with respecting the user's wish for a custom URI. The .NET localtunnel server uses Kestrel under the hood and can be configured with the appsettings.json file. You can mount a custom appsettings.json file with a JSON configuration to support HTTPS by specifying a custom certificate. You can also use NGINX as a reverse proxy, proxying to the endpoint of the localtunnel API.

**Comment by sundayScoop** [comment]
When you say open all the ports, are you saying a public server would need ALL of their ports open to the internet for the localtunnel server to work?

**Comment by angelobreuer** [comment]
It depends on the operating system what ports are called by definition "any available port" but yes that is right. I am aware of the security risks. 

The project itself was long before only a localtunnel client which was only meant to be compatible with the original localtunnel server written in NodeJS. The localtunnel C# server was implemented because of high demand of a .NET version. There are tons of vulnerabilities that come up with such a design (easy hijacking of other tunnels, a public server with all ports open, and much more). If you run a simple Nmap scan against the official localtunnel server, you can easily identify other tunnels and their corresponding ports.

It is easily to implement a localtunnel-like server without all these vulnerabilities and way more efficiency, but it would never be possible without harming compability with the original localtunnel idea. The subject of this project is to guarantee compability.

I do not know what the original intention of the localtunnel project was, but I always had the feeling that localtunnel is absolutely only meant to be a tool for ease of development.

---

![image](https://user-images.githubusercontent.com/46497296/210978266-0a7aff87-a7ee-4f7f-ade1-3da6b7989eee.png)
(Source: https://github.com/localtunnel/server#deploy)

**Comment by sundayScoop** [comment]
Thanks for the insight.

After some tinkering I managed to get the server running publicly with an nginx in front of it.
Great project. 

I'll be closing this issue.
